title: Coral
description: A simple library for playing .wav files.
baseurl: "Coral"
url: "https://colorprogrammy.github.io"

theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: /blog/page:num/

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span: false
    line_numbers: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/

# SEO Optimization
plugins:
  - jekyll-seo-tag

# Exclude files from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
